include_guard(GLOBAL)

function(reaktio_texture_sanitize_asset_name INPUT OUTPUT_VAR)
    string(TOLOWER "${INPUT}" sanitized)
    string(REGEX REPLACE "[^a-z0-9]+" "-" sanitized "${sanitized}")
    string(REGEX REPLACE "^-+" "" sanitized "${sanitized}")
    string(REGEX REPLACE "-+$" "" sanitized "${sanitized}")
    if("${sanitized}" STREQUAL "")
        set(sanitized "texture")
    endif()
    set(${OUTPUT_VAR} "${sanitized}" PARENT_SCOPE)
endfunction()

function(reaktio_texture_normalize_bool INPUT_VALUE DEFAULT_VALUE OUTPUT_VAR)
    if("${INPUT_VALUE}" STREQUAL "")
        set(${OUTPUT_VAR} ${DEFAULT_VALUE} PARENT_SCOPE)
        return()
    endif()

    string(TOLOWER "${INPUT_VALUE}" lowered)
    if(lowered STREQUAL "true" OR lowered STREQUAL "1" OR lowered STREQUAL "yes" OR lowered STREQUAL "on")
        set(${OUTPUT_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    if(lowered STREQUAL "false" OR lowered STREQUAL "0" OR lowered STREQUAL "no" OR lowered STREQUAL "off")
        set(${OUTPUT_VAR} FALSE PARENT_SCOPE)
        return()
    endif()

    message(FATAL_ERROR "Invalid boolean value '${INPUT_VALUE}' in texture manifest.")
endfunction()

function(reaktio_texture_resolve_platform_defaults USAGE OUT_CONTAINER OUT_FORMAT OUT_LINEAR OUT_NORMALMAP OUT_MIPS)
    string(TOLOWER "${USAGE}" usage_lower)
    if(NOT usage_lower STREQUAL "color_opaque"
       AND NOT usage_lower STREQUAL "color_alpha"
       AND NOT usage_lower STREQUAL "normal_map"
       AND NOT usage_lower STREQUAL "ui")
        message(FATAL_ERROR "Unsupported texture usage '${USAGE}'. Expected color_opaque, color_alpha, normal_map, or ui.")
    endif()

    set(container "ktx")
    set(format "RGBA8")
    set(linear FALSE)
    set(normalmap FALSE)
    set(mips TRUE)

    if(usage_lower STREQUAL "ui")
        set(mips FALSE)
    elseif(usage_lower STREQUAL "normal_map")
        set(linear TRUE)
        set(normalmap TRUE)
    endif()

    if(WIN32 OR MINGW OR MSYS OR CYGWIN)
        set(container "dds")
        if(usage_lower STREQUAL "color_opaque")
            set(format "BC1")
        elseif(usage_lower STREQUAL "color_alpha")
            set(format "BC3")
        elseif(usage_lower STREQUAL "normal_map")
            set(format "BC5")
        elseif(usage_lower STREQUAL "ui")
            set(format "RGBA8")
        endif()
    endif()

    set(${OUT_CONTAINER} "${container}" PARENT_SCOPE)
    set(${OUT_FORMAT} "${format}" PARENT_SCOPE)
    set(${OUT_LINEAR} ${linear} PARENT_SCOPE)
    set(${OUT_NORMALMAP} ${normalmap} PARENT_SCOPE)
    set(${OUT_MIPS} ${mips} PARENT_SCOPE)
endfunction()

function(reaktio_cook_texture_manifest)
    set(options "")
    set(oneValueArgs MANIFEST_FILE COOKED_ROOT TARGET_NAME)
    set(multiValueArgs "")
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_MANIFEST_FILE OR NOT ARG_COOKED_ROOT OR NOT ARG_TARGET_NAME)
        message(FATAL_ERROR "reaktio_cook_texture_manifest requires MANIFEST_FILE, COOKED_ROOT, and TARGET_NAME.")
    endif()

    if(NOT EXISTS "${ARG_MANIFEST_FILE}")
        message(FATAL_ERROR "Texture authoring manifest does not exist: ${ARG_MANIFEST_FILE}")
    endif()

    get_filename_component(manifest_dir "${ARG_MANIFEST_FILE}" DIRECTORY)
    file(READ "${ARG_MANIFEST_FILE}" manifest_text)
    string(REPLACE "\r\n" "\n" manifest_text "${manifest_text}")
    string(REPLACE "\r" "\n" manifest_text "${manifest_text}")
    string(REPLACE "\n" ";" manifest_lines "${manifest_text}")

    set(texture_outputs "")
    set(current_section "")
    set(current_runtime_label "")
    set(current_source "")
    set(current_width "")
    set(current_height "")
    set(current_usage "")
    set(current_quality "default")
    set(current_mips "")
    set(current_max_size "")
    set(current_premultiply_alpha "")
    set(current_format_override "")
    set(current_container_override "")
    set(current_linear_override "")
    set(current_output_name "")

    macro(reaktio_finalize_current_texture_section)
        if(NOT "${current_section}" STREQUAL "")
            if(current_section MATCHES "^texture\.(.+)$")
                set(texture_id "${CMAKE_MATCH_1}")
                if("${current_runtime_label}" STREQUAL "" OR "${current_source}" STREQUAL "" OR "${current_width}" STREQUAL "" OR "${current_height}" STREQUAL "" OR "${current_usage}" STREQUAL "")
                    message(FATAL_ERROR "Texture manifest section [${current_section}] is missing runtime_label, source, width, height, or usage.")
                endif()

                reaktio_texture_resolve_platform_defaults(
                    "${current_usage}"
                    resolved_container
                    resolved_format
                    resolved_linear
                    resolved_normalmap
                    resolved_mips)
                if(NOT "${current_format_override}" STREQUAL "")
                    set(resolved_format "${current_format_override}")
                endif()
                if(NOT "${current_container_override}" STREQUAL "")
                    set(resolved_container "${current_container_override}")
                endif()
                if(NOT "${current_linear_override}" STREQUAL "")
                    reaktio_texture_normalize_bool("${current_linear_override}" ${resolved_linear} resolved_linear)
                endif()
                if(NOT "${current_mips}" STREQUAL "")
                    reaktio_texture_normalize_bool("${current_mips}" ${resolved_mips} resolved_mips)
                endif()
                if(NOT "${current_premultiply_alpha}" STREQUAL "")
                    reaktio_texture_normalize_bool("${current_premultiply_alpha}" FALSE resolved_premultiply_alpha)
                else()
                    set(resolved_premultiply_alpha FALSE)
                endif()

                set(source_path "${manifest_dir}/${current_source}")
                if(NOT EXISTS "${source_path}")
                    message(FATAL_ERROR "Texture source does not exist: ${source_path}")
                endif()

                if("${current_output_name}" STREQUAL "")
                    get_filename_component(texture_stem "${current_source}" NAME_WE)
                else()
                    set(texture_stem "${current_output_name}")
                endif()
                reaktio_texture_sanitize_asset_name("${texture_stem}" texture_stem)

                set(container_output "${ARG_COOKED_ROOT}/${texture_stem}.${resolved_container}")
                set(metadata_output "${ARG_COOKED_ROOT}/${texture_stem}.texture.ini")
                get_filename_component(container_filename "${container_output}" NAME)
                set(texture_compile_args
                    FILE "${source_path}"
                    OUTPUT "${container_output}"
                    FORMAT "${resolved_format}"
                    QUALITY "${current_quality}"
                    AS "${resolved_container}")
                if(resolved_mips)
                    list(APPEND texture_compile_args MIPS)
                endif()
                if(resolved_linear)
                    list(APPEND texture_compile_args LINEAR)
                endif()
                if(resolved_normalmap)
                    list(APPEND texture_compile_args NORMALMAP)
                endif()
                if(resolved_premultiply_alpha)
                    list(APPEND texture_compile_args PMA)
                endif()
                if(NOT "${current_max_size}" STREQUAL "")
                    list(APPEND texture_compile_args MAX "${current_max_size}")
                endif()

                bgfx_compile_texture(${texture_compile_args})

                if(resolved_linear)
                    set(metadata_srgb false)
                else()
                    set(metadata_srgb true)
                endif()

                set(generated_metadata_input "${CMAKE_CURRENT_BINARY_DIR}/${ARG_TARGET_NAME}-${texture_stem}.generated.ini")
                set(metadata_content
"[texture]\nstorage = ${resolved_container}\nformat = ${resolved_format}\nwidth = ${current_width}\nheight = ${current_height}\nsrgb = ${metadata_srgb}\ngenerate_mips = $<IF:$<BOOL:${resolved_mips}>,true,false>\npayload = ${container_filename}\n")
                file(GENERATE OUTPUT "${generated_metadata_input}" CONTENT "${metadata_content}")

                add_custom_command(
                    OUTPUT "${metadata_output}"
                    COMMAND ${CMAKE_COMMAND} -E make_directory "${ARG_COOKED_ROOT}"
                    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${generated_metadata_input}" "${metadata_output}"
                    DEPENDS "${generated_metadata_input}" "${container_output}"
                    VERBATIM
                )

                list(APPEND texture_outputs "${container_output}" "${metadata_output}")
            elseif(NOT current_section STREQUAL "meta")
                message(FATAL_ERROR "Unsupported texture manifest section [${current_section}].")
            endif()
        endif()
    endmacro()

    foreach(raw_line IN LISTS manifest_lines)
        string(STRIP "${raw_line}" line)
        if("${line}" STREQUAL "" OR line MATCHES "^[#;]")
            continue()
        endif()

        if(line MATCHES "^\\[(.+)\\]$")
            set(next_section "${CMAKE_MATCH_1}")
            reaktio_finalize_current_texture_section()
            set(current_section "${next_section}")
            set(current_runtime_label "")
            set(current_source "")
            set(current_width "")
            set(current_height "")
            set(current_usage "")
            set(current_quality "default")
            set(current_mips "")
            set(current_max_size "")
            set(current_premultiply_alpha "")
            set(current_format_override "")
            set(current_container_override "")
            set(current_linear_override "")
            set(current_output_name "")
            continue()
        endif()

        string(FIND "${line}" "=" separator)
        if(separator EQUAL -1)
            message(FATAL_ERROR "Texture manifest line is missing '=': ${line}")
        endif()

        math(EXPR value_start "${separator} + 1")
        string(SUBSTRING "${line}" 0 ${separator} key)
        string(SUBSTRING "${line}" ${value_start} -1 value)
        string(STRIP "${key}" key)
        string(STRIP "${value}" value)

        if(current_section MATCHES "^texture\\.")
            if(key STREQUAL "runtime_label")
                set(current_runtime_label "${value}")
            elseif(key STREQUAL "source")
                set(current_source "${value}")
            elseif(key STREQUAL "width")
                set(current_width "${value}")
            elseif(key STREQUAL "height")
                set(current_height "${value}")
            elseif(key STREQUAL "usage")
                set(current_usage "${value}")
            elseif(key STREQUAL "quality")
                set(current_quality "${value}")
            elseif(key STREQUAL "mips")
                set(current_mips "${value}")
            elseif(key STREQUAL "max_size")
                set(current_max_size "${value}")
            elseif(key STREQUAL "premultiply_alpha")
                set(current_premultiply_alpha "${value}")
            elseif(key STREQUAL "format_override")
                set(current_format_override "${value}")
            elseif(key STREQUAL "container_override")
                set(current_container_override "${value}")
            elseif(key STREQUAL "linear")
                set(current_linear_override "${value}")
            elseif(key STREQUAL "output_name")
                set(current_output_name "${value}")
            else()
                message(FATAL_ERROR "Unsupported key '${key}' in texture manifest section [${current_section}].")
            endif()
        endif()
    endforeach()

    reaktio_finalize_current_texture_section()

    if(texture_outputs STREQUAL "")
        message(FATAL_ERROR "Texture manifest did not define any textures: ${ARG_MANIFEST_FILE}")
    endif()

    add_custom_target(${ARG_TARGET_NAME} DEPENDS ${texture_outputs})
endfunction()